baseURL = "https://blog.muehlburger.at"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
googleAnalytics = "UA-131790127-1"

#disqusShortname = "muehlburger"

[params]
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "blog.muehlburger.at"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/muehlburger/"

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/hmuehlburger/"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/herbert-muehlburger/"

[[params.social]]
    name = "RSS"
    icon = "fas fa-rss-square"
    weight = 4
    url = "/index.xml"

[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
        title = "muehlburger.at"

        # You can configure the theme parameter for each language.
        [languages.en.params]
            author = "Herbert Muehlburger"
            info = "Solution Architect and Senior Software Engineer"
            description = "Herbert Muehlburger's personal website"
            keywords = "blog, developer"

        [languages.en.menu] # It is possible to change the menu too.

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/posts/"

    [languages.de]
        languagename = "Deutsch"
        title = "muehlburger.at"

        [languages.de.params]
            author = "Herbert Mühlburger"
            info = "Solution Architect und Senior Software Engineer"
            description = "Herbert Mühlburgers Website"
            keywords = "blog, developer"

        [languages.de.menu]

            [[languages.de.menu.main]]
            name = "Über mich"
            weight = 1
            url = "/de/about/"

            [[languages.de.menu.main]]
            name = "Blog"
            weight = 2
            url = "/de/posts/"

