baseurl = "/"
title = "DI Herbert Mühlburger"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"
googleAnalytics = "UA-131790127-1"

[params]
    author = "DI Herbert Mühlburger"
    description = "Experienced Technology Architect and Senior Software Engineer."
    keywords = "Mühlburger, Muehlburger, Information Technology, IT, Herbert Mühlburger, Herbert Muehlburger, Technology Architect, Senior Software Engineer"
    info = "Technology Architect // Senior Software Engineer"
    avatarurl = "images/avatar.jpg"
    footercontent = "🔥for tech"

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/muehlburger/muehlburger.github.io.git/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = ["css/cookieconsent.min.css"]

    # Custom JS
    custom_js = ["js/cookieconsent.min.js", "js/init-cookieconsent.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/muehlburger/"

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/hmuehlburger/"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/herbert-muehlburger/"

[[params.social]]
    name = "RSS"
    icon = "fas fa-rss-square"
    weight = 4
    url = "index.xml"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.params]

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 2
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 1
            url = "posts/"

    [languages.de]
        languagename = "Deutsch"
        title = "DI Herbert Mühlburger"

        [languages.de.params]
            keywords = "Mühlburger, Softwareentwicklung - Wirtschaft, DSGVO, Datenschutz, Datenschutzzertifizierung, Zertifikat, IT, Informatik, Herbert Mühlburger, Technology Architekt, Senior Software Entwickler, Software Architekt"

        [languages.de.menu]

            [[languages.de.menu.main]]
            name = "Blog"
            weight = 1
            url = "posts/"

            [[languages.de.menu.main]]
            name = "About"
            weight = 2
            url = "about/"
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false
