baseURL = "https://blog.muehlburger.at"
title = "Herbert Mühlburger"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
    author = "Herbert Mühlburger"
    description = "Experienced Technology Architect and Senior Software Engineer."
    keywords = "Herbert Mühlburger, Herbert Muehlburger, Technology Architect, Senior Software Engineer"
    info = "Technology Architect // Senior Software Engineer"
    avatarurl = "images/avatar.jpg"
#    footercontent = "Enter a text here."

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/muehlburger/muehlburger.github.io.git/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = ["css/custom.css"]

[taxonomies]
  series = "series"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/muehlburger/"

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/hmuehlburger/"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/herbert-muehlburger/"

[[params.social]]
    name = "RSS"
    icon = "fas fa-rss-square"
    weight = 4
    url = "/index.xml"

[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.

        # You can configure the theme parameter for each language.
        [languages.en.params]

        [languages.en.menu] # It is possible to change the menu too.

        [[languages.en.menu.main]]
        name = "About"
        weight = 2
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 1
        url = "/posts/"

    [languages.de]
        languagename = "Deutsch"

        [languages.de.params]
            keywords = "blog, developer"

        [languages.de.menu]

            [[languages.de.menu.main]]
            name = "Blog"
            weight = 1
            url = "/de/posts/"

            [[languages.de.menu.main]]
            name = "About"
            weight = 2
            url = "/de/about/"