baseURL = "https://blog.muehlburger.at"
title = "muehlburger.at"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
googleAnalytics = "UA-131790127-1"

#disqusShortname = "muehlburger"

[params]
    author = "Herbert Mühlburger"
    info = "Solution Architect and Senior Software Engineer"
    description = "Herbert Mühlburger's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "blog.muehlburger.at"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/muehlburger/"

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/hmuehlburger/"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/herbert-muehlburger/"

[[params.social]]
    name = "RSS"
    icon = "fas fa-rss-square"
    weight = 4
    url = "/index.xml"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts"

[[menu.main]]
    name = "About me"
    weight = 2
    url = "/about/"